### ISSUE TITLE
I need Help

### ISSUE THREAD

**Issue by RedHeadt228** [Mohamashi/SAFER-plus-realization#1]
I'm writing a similar program, but I can't find the working code for the DLL, please help me and send the code Safer+DLL.dll . I will be very grateful for your help.

**Comment by Mohamashi** [comment]
Safer+DLL.dll file is correct dll. At least it should be.

**Comment by RedHeadt228** [comment]
Safer+.dll works fine in this there is no problem. I need the source code of the dll, since I don't understand what is going on in encrypt_block and decrypt_block, I will be grateful if you post it.
